updates to ajentvee, alleemac (alleemac bio unfinishied)
meastoso/rainbowarcade_website pull request #3
Opened 2020-10-06 04:59 UTC by cheratomo

2020-10-12 20:41 UTC, cheratomo commented
add members A-D

2020-10-12 21:57 UTC, meastoso commented on ra-admin/members.json
> +      "image": "ajentvee.png"
Image references are case sensitive. Looks like the file you added is "AjentVee.png" so just align the capitalization here as well.

2020-10-12 21:59 UTC, meastoso reviewed
The file name added is: "Copy of AlleeMac_RainbowArcade_Headshot.png". This format with spaces will cause issues when the page loads when finding the file. Please use more simple filenames with no special characters beyond hyphens or underscores.

2020-10-12 22:00 UTC, meastoso requested changes
Please use simple filenames for photos, this won't get picked-up by the website properly.

2020-10-12 22:21 UTC, cheratomo commented
Updated - photo files fixed!

2020-10-13 05:48 UTC, cheratomo commented
added the rest of the members to photos/members.json; have some concern about whether non-vanity youtube channel links will work in this format

2020-10-15 17:21 UTC, merged